game:
  parameters:
    rows: 5
    cells: 5
    bombs: 7
springdoc:
  use-management-port: true
management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include:
          - openapi
          - swaggerui
